  
# This master script will be built to replicate all plots from the Giant Virus paper which
# were generated by the R package Circlize


########################################################
########################################################

### Sections

# 1. Install and Load required Packages
# 2. Import and manipulate the data for extended figure 4
# 3. Replicate Extended figure 4
# TBD

########################################################
########################################################

# Section 1: Install and Load required Packages 

  install.packages("circlize")
  install.packages("GFF")
  install.packages("Rtools")
  install.packages("ape")
  
  # Commented these out because I'm not sure if they are really needed
  #install.packages("BiocManager")
  #BiocManager::install("genbankr")
  #library(BiocManager)
  
  library(circlize)
  library(ape)
  
########################################################
########################################################
  
# Section 2: Import and manipulate the data for extended figure 4 
  
  setwd("C:/Users/tyler/Desktop/test")
  
  
  # read idea from from https://www.rdocumentation.org/packages/ape/versions/5.4-1/topics/read.gff
  AUG_GEVE1 <-read.gff("AUG_eustigma.gff")
  AUG_GEVE2 <-read.gff("AUG_eustigma2.gff")
  PRG_GEVE1 <-read.gff("prodigal_eustigma")
  PRG_GEVE2 <-read.gff("prodigal_eustigma2")
  
  #AUG_GEVE1 <- AUG_GEVE1[(AUG_GEVE1$type=="gene"),]
  #PRG_GEVE1 <- PRG_GEVE1[(PRG_GEVE1$type=="gene"),]
  #AUG_GEVE2 <- AUG_GEVE2[(AUG_GEVE2$type=="gene"),]
  #PRG_GEVE2 <- PRG_GEVE2[(PRG_GEVE2$type=="gene"),]
  
  # get only the 4 coloumns seqid, start, end and attributes. Idea from https://www.listendata.com/2015/06/r-keep-drop-columns-from-data-frame.html
  AUG_GEVE1 <- subset(AUG_GEVE1,select = +c(seqid,start,end,attributes))
  AUG_GEVE2 <- subset(AUG_GEVE2,select = +c(seqid,start,end,attributes))
  PRG_GEVE1 <- subset(PRG_GEVE1,select = +c(seqid,start,end,attributes))
  PRG_GEVE2 <- subset(PRG_GEVE2,select = +c(seqid,start,end,attributes))
  
 
 
  
  
########################################################
########################################################
  
  # Section 3: Replicate Extended figure 4 
  
  # idea from section 9.3 of https://jokergoo.github.io/circlize_book/book/initialize-genomic-plot.html#initialize-with-general-genomic-category
  
  # Create GEVE1 plot
  circos.par("start.degree" = 90)
  circos.genomicInitialize(AUG_GEVE1,plotType=NULL)
  #circos.track(ylim = c(0, 1), bg.border = "black", track.height = 0.1)
  a1 = max(tapply(AUG_GEVE1$attributes,AUG_GEVE1$seqid, function(x) length(unique(x))))
  circos.genomicTrack(AUG_GEVE1, ylim = c(0.5, n + 0.5), 
                      panel.fun = function(region, value, ...) {
                        all_tx = unique(value$attributes)
                        for(i in seq_along(all_tx)) {
                          l = value$attributes == all_tx[i]
                          current_tx_start = min(region[l, 1])
                          current_tx_end = max(region[l, 2])
                          circos.lines(x=c(current_tx_start, current_tx_end),y=c(40,40), col = "brown", area=TRUE )
                        }
                      }, bg.border = "black", track.height = 0.1)
  p1 = max(tapply(PRG_GEVE1$attributes,PRG_GEVE1$seqid, function(x) length(unique(x))))
  circos.genomicTrack(PRG_GEVE1, ylim = c(0.5, n + 0.5), 
                      panel.fun = function(region, value, ...) {
                        all_tx = unique(value$attributes)
                        for(i in seq_along(all_tx)) {
                          l = value$attributes == all_tx[i]
                          # for each transcript
                          current_tx_start = min(region[l, 1])
                          current_tx_end = max(region[l, 2])
                          circos.lines(x=c(current_tx_start, current_tx_end),y=c(40,40), col = "green", area=TRUE)
                        }
                      }, bg.border = "black", track.height = 0.1)
  title("C. eustigma GEVE 1")
  
  # Create GEVE 2 plot
  circos.genomicInitialize(AUG_GEVE2,plotType=NULL)
  #circos.track(ylim = c(0, 1), bg.border = "black", track.height = 0.1)
  a2 = max(tapply(AUG_GEVE2$attributes,AUG_GEVE2$seqid, function(x) length(unique(x))))
  circos.genomicTrack(AUG_GEVE2, ylim = c(0.5, n + 0.5), 
                      panel.fun = function(region, value, ...) {
                        all_tx = unique(value$attributes)
                        for(i in seq_along(all_tx)) {
                          l = value$attributes == all_tx[i]
                          current_tx_start = min(region[l, 1])
                          current_tx_end = max(region[l, 2])
                          circos.lines(x=c(current_tx_start, current_tx_end),y=c(40,40), col = "brown", area=TRUE )
                        }
                      }, bg.border = "black", track.height = 0.1)
  p2 = max(tapply(PRG_GEVE2$attributes,PRG_GEVE2$seqid, function(x) length(unique(x))))
  circos.genomicTrack(PRG_GEVE2, ylim = c(0.5, n + 0.5), 
                      panel.fun = function(region, value, ...) {
                        all_tx = unique(value$attributes)
                        for(i in seq_along(all_tx)) {
                          l = value$attributes == all_tx[i]
                          # for each transcript
                          current_tx_start = min(region[l, 1])
                          current_tx_end = max(region[l, 2])
                          circos.lines(x=c(current_tx_start, current_tx_end),y=c(40,40), col = "green", area=TRUE)
                        }
                      }, bg.border = "black", track.height = 0.1)
  title("C. eustigma GEVE 2")
  circos.clear()
  
  